
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.imagegenerator.datareader;

/** CUP generated class containing symbol constants. */
public class symCapa {
  /* terminals */
  public static final int COLOR = 9;
  public static final int COMA = 2;
  public static final int SEMI_COLON = 6;
  public static final int COLON = 5;
  public static final int NUMBER = 7;
  public static final int EOF = 0;
  public static final int OPEN_CURLY = 3;
  public static final int ID = 8;
  public static final int error = 1;
  public static final int CLOSE_CURLY = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "OPEN_CURLY",
  "CLOSE_CURLY",
  "COLON",
  "SEMI_COLON",
  "NUMBER",
  "ID",
  "COLOR"
  };
}

